service: ticketing-bot-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    NODE_ENV: ${sls:stage}

functions:
  xia-ticketing:
    handler: handler.xia
    events:
      - schedule: cron(40 0-23 * * ? *)

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
